# Generated by Django 4.1.5 on 2023-02-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP2", "0002_messagetoform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="phone",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
