# Generated by Django 4.1.5 on 2023-02-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("APP2", "0004_registration_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="Status",
        ),
    ]
