# Generated by Django 4.1.5 on 2023-02-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP2", "0005_remove_registration_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
